defaultPlacement: end
enableVersioning: true
handle: albums
name: Albums
propagationMethod: all
siteSettings:
  18990027-5eed-431d-bdce-ee7f4879399c: # Songapp
    enabledByDefault: true
    hasUrls: true
    template: albums/_entry
    uriFormat: 'albums/{slug}'
type: channel
