defaultPlacement: end
enableVersioning: true
handle: songs
name: Songs
propagationMethod: all
siteSettings:
  18990027-5eed-431d-bdce-ee7f4879399c: # Songapp
    enabledByDefault: true
    hasUrls: true
    template: songs/_entry
    uriFormat: 'songs/{slug}'
type: channel
